# Generated by Django 2.2.20 on 2021-08-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20210826_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snitch', models.CharField(max_length=200, verbose_name='Имя осведомителя')),
                ('reported_flat_name', models.CharField(max_length=200, verbose_name='Обвиняемая квартира')),
                ('text', models.TextField(verbose_name='Текст жалобы')),
                ('reported_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Flat')),
            ],
        ),
    ]
