# Generated by Django 2.2.20 on 2021-08-28 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_flat_name',
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Flat', verbose_name='Обвиняемая квартира'),
        ),
        migrations.AlterField(
            model_name='report',
            name='snitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Осведомитель'),
        ),
    ]
