# Generated by Django 2.2.20 on 2021-08-31 18:29

from django.db import migrations


def refill_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )[0]
        owner.apartments_in_property.add(flat)
        Owner.save(owner)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    all_owners = Owner.objects.all()
    all_owners.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210831_1544'),
    ]

    operations = [
        migrations.RunPython(refill_data, move_backward)
    ]
