# Generated by Django 2.2.20 on 2021-09-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210901_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(db_index=True, verbose_name='Является ли новостройкой'),
        ),
    ]
