# Generated by Django 2.2.20 on 2021-09-11 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20210911_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(related_name='Liked_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, лайкнвушиее пост'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accused_flat', to='property.Flat', verbose_name='Обвиняемая квартира'),
        ),
        migrations.AlterField(
            model_name='report',
            name='snitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Informer', to=settings.AUTH_USER_MODEL, verbose_name='Осведомитель'),
        ),
    ]
